//
// Created by Wu Alex on 2020/2/14.
//

#ifndef NEWFREERTOS_FREERTOSCONFIG_H
#define NEWFREERTOS_FREERTOSCONFIG_H

#define configUSE_16_BIT_TICKS 0
#define configMax_TASK_NAME_LEN 16
#define configSUPPORT_STATIC_ALLOCATION 1



#endif //NEWFREERTOS_FREERTOSCONFIG_H
